# Generated by Django 5.2.6 on 2026-06-27 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuroraProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tier', models.IntegerField(default=0)),
                ('max_aurora_level', models.IntegerField(default=0, help_text='Maximum Aurora Level for this property')),
            ],
            options={
                'verbose_name': 'Aurora Property',
                'verbose_name_plural': 'Aurora Properties',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LumenTierProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tier', models.IntegerField()),
                ('max_lumen_level', models.IntegerField(default=0, help_text='Maximum Lumen Ascend Level for this tier')),
                ('heavy_failure_level', models.IntegerField(default=0, help_text='Level to drop to on heavy failure')),
            ],
            options={
                'verbose_name': 'Lumen Tier Property',
                'verbose_name_plural': 'Lumen Tier Properties',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='AuroraLinePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('pendant', 'Pendant'), ('earring', 'Earring'), ('ring', 'Ring'), ('belt', 'Belt'), ('face', 'Face Accessory'), ('eye', 'Eye Accessory'), ('hat', 'Hat'), ('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('cape', 'Cape'), ('gloves', 'Gloves'), ('shoulder', 'Shoulder Armor'), ('weapon', 'Weapon'), ('use', 'Consumable'), ('etc', 'Etc')], help_text='Item type', max_length=20)),
                ('aurora_level', models.IntegerField(help_text='Aurora Level')),
                ('stat_type', models.CharField(choices=[('hp', 'HP'), ('mp', 'MP'), ('att', 'Attack'), ('str', 'Strength'), ('agi', 'Agility'), ('int', 'Intelligence'), ('all', 'All Stats'), ('drop', 'Drop Rate')], help_text='Type of the line that stat boost', max_length=20)),
                ('line_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], help_text='Type of the line', max_length=20)),
                ('value', models.FloatField(help_text='Value of the line')),
                ('weight', models.IntegerField(default=1, help_text='Relative weight for random selection')),
                ('aurora_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_pools', to='items.auroraproperty')),
            ],
            options={
                'verbose_name': 'Aurora Line Pool',
                'verbose_name_plural': 'Aurora Line Pools',
                'ordering': ['aurora_property', 'item_type', 'aurora_level', 'stat_type', 'line_type', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ItemSetEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_count', models.IntegerField()),
                ('hp_boost', models.IntegerField(default=0)),
                ('mp_boost', models.IntegerField(default=0)),
                ('att_boost', models.IntegerField(default=0)),
                ('str_boost', models.IntegerField(default=0)),
                ('agi_boost', models.IntegerField(default=0)),
                ('int_boost', models.IntegerField(default=0)),
                ('all_stats_boost', models.IntegerField(default=0)),
                ('item_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='items.itemset')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('pendant', 'Pendant'), ('earring', 'Earring'), ('ring', 'Ring'), ('belt', 'Belt'), ('face', 'Face Accessory'), ('eye', 'Eye Accessory'), ('hat', 'Hat'), ('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('cape', 'Cape'), ('gloves', 'Gloves'), ('shoulder', 'Shoulder Armor'), ('weapon', 'Weapon'), ('use', 'Consumable'), ('etc', 'Etc')], max_length=20)),
                ('weapon_type', models.CharField(blank=True, choices=[('1hs', 'One Handed Sword'), ('2hs', 'Two Handed Sword'), ('1ha', 'One Handed Axe'), ('bow', 'Bow'), ('staff', 'Staff'), ('wand', 'Wand'), ('spear', 'Spear')], max_length=20, null=True)),
                ('minimum_level', models.IntegerField(default=1)),
                ('is_tradeable', models.BooleanField(default=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('hp_boost', models.IntegerField(default=0)),
                ('mp_boost', models.IntegerField(default=0)),
                ('att_boost', models.IntegerField(default=0)),
                ('str_boost', models.IntegerField(default=0)),
                ('agi_boost', models.IntegerField(default=0)),
                ('int_boost', models.IntegerField(default=0)),
                ('all_stats_boost', models.IntegerField(default=0)),
                ('drop_rate_boost', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
                ('sell_price', models.IntegerField(default=1)),
                ('aurora_tier', models.ForeignKey(blank=True, help_text='Aurora Tier for this item (if upgradable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.auroraproperty')),
                ('class_restriction', models.ManyToManyField(blank=True, to='classes.characterclass')),
                ('job_restriction', models.ManyToManyField(blank=True, to='classes.job')),
                ('lumen_tier', models.ForeignKey(blank=True, help_text='Lumen Tier for this item (if upgradable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.lumentierproperty')),
            ],
        ),
        migrations.AddField(
            model_name='itemset',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='item_sets', to='items.itemtemplate'),
        ),
        migrations.CreateModel(
            name='LumenCostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=0, help_text='Current Lumen Ascend Level before attempting')),
                ('lumis_cost', models.BigIntegerField(default=0, help_text='Cost in Lumis to attempt ascend')),
                ('success_rate', models.FloatField(default=1.0, help_text='Success rate, item level increase', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('failure_rate', models.FloatField(default=0.0, help_text='Failure rate, item do not change', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('heavy_failure_rate', models.FloatField(default=0.0, help_text='Heavy failure rate, item lost level to certain point', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('lumen_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_rules', to='items.lumentierproperty')),
            ],
            options={
                'verbose_name': 'Lumen Cost Rule',
                'verbose_name_plural': 'Lumen Cost Rules',
                'ordering': ['lumen_tier', 'current_level'],
            },
        ),
        migrations.CreateModel(
            name='LumenAscendRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('pendant', 'Pendant'), ('earring', 'Earring'), ('ring', 'Ring'), ('belt', 'Belt'), ('face', 'Face Accessory'), ('eye', 'Eye Accessory'), ('hat', 'Hat'), ('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('cape', 'Cape'), ('gloves', 'Gloves'), ('shoulder', 'Shoulder Armor'), ('weapon', 'Weapon'), ('use', 'Consumable'), ('etc', 'Etc')], help_text='Item type applicable for this rule', max_length=20)),
                ('lumen_level', models.PositiveIntegerField(help_text='Lumen Ascend Level')),
                ('hp_boost', models.IntegerField(default=0)),
                ('mp_boost', models.IntegerField(default=0)),
                ('att_boost', models.IntegerField(default=0)),
                ('str_boost', models.IntegerField(default=0)),
                ('agi_boost', models.IntegerField(default=0)),
                ('int_boost', models.IntegerField(default=0)),
                ('lumen_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascend_rules', to='items.lumentierproperty')),
            ],
            options={
                'verbose_name': 'Lumen Ascend Stat Rule',
                'verbose_name_plural': 'Lumen Ascend Stat Rules',
                'ordering': ['lumen_tier', 'item_type', 'lumen_level'],
                'unique_together': {('lumen_tier', 'item_type', 'lumen_level')},
            },
        ),
    ]
