# Generated by Django 5.2.6 on 2026-06-27 09:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuroraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('tier_up_chance_multiplier', models.FloatField(default=1.0, help_text='Multiplier for Aurora tier-up rate (e.g. 1.5 for 1.5x tier-up chance)')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aurora Event',
                'verbose_name_plural': 'Aurora Events',
            },
        ),
        migrations.CreateModel(
            name='LumenEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('success_flat_bonus', models.FloatField(default=0.0, help_text='Flat bonus to success rate (e.g. 0.05 for +5%)')),
                ('heavy_failure_multiplier', models.FloatField(default=1.0, help_text='Multiplier for heavy failure rate (e.g. 0.0 for no boom, 0.5 for half boom)')),
                ('bonus_levels', models.IntegerField(default=0, help_text='Extra levels gained on success (e.g. 1 means +2 levels total)')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lumen Event',
                'verbose_name_plural': 'Lumen Events',
            },
        ),
        migrations.CreateModel(
            name='AuroraModifierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_type', models.CharField(choices=[('REROLL_ALL', 'Reroll All Lines (Basic)'), ('REROLL_CHOICE', 'Reroll All Lines & Choose (Before/After)'), ('REROLL_TRIPLE_CHOICE', 'Reroll 3x Lines & Pick N'), ('REROLL_SINGLE', 'Reroll a Single Selected Line'), ('REPLACE_FIXED', 'Replace Single Line with Fixed Stat'), ('REPLACE_SELECT', 'Replace Single Line with Selected Stat'), ('FORCE_SET', 'Force Set Aurora Level and Fixed Lines')], max_length=50)),
                ('tier_up_chance', models.FloatField(default=0.0, help_text='Base chance to tier-up (increase Aurora Level) if applicable', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('forced_aurora_level', models.IntegerField(blank=True, help_text='For FORCE_SET: The exact Aurora level to force the item to', null=True)),
                ('fixed_stat_type', models.CharField(blank=True, choices=[('hp', 'HP'), ('mp', 'MP'), ('att', 'Attack'), ('str', 'Strength'), ('agi', 'Agility'), ('int', 'Intelligence'), ('all', 'All Stats'), ('drop', 'Drop Rate')], max_length=20, null=True)),
                ('fixed_line_type', models.CharField(blank=True, choices=[('flat', 'Flat'), ('percent', 'Percent')], max_length=20, null=True)),
                ('fixed_value', models.FloatField(blank=True, null=True)),
                ('item_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aurora_modifier_rule', to='items.itemtemplate')),
                ('max_aurora_target', models.ForeignKey(help_text='Max Aurora Level this item can affect', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='items.auroraproperty')),
            ],
            options={
                'verbose_name': 'Aurora Modifier Rule',
                'verbose_name_plural': 'Aurora Modifier Rules',
            },
        ),
    ]
