# Generated by Django 5.2.6 on 2026-06-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='is_trade_once',
            field=models.BooleanField(default=False, help_text='If True, item becomes untradeable after 1 trade'),
        ),
    ]
