# Generated by Django 5.2.6 on 2026-06-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemtemplate_is_trade_once'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lumentierproperty',
            name='heavy_failure_level',
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='weapon_type',
            field=models.CharField(blank=True, choices=[('1hs', 'One Handed Sword'), ('2hs', 'Two Handed Sword'), ('1ha', 'One Handed Axe'), ('blunt', 'Blunt Weapon'), ('bow', 'Bow'), ('staff', 'Staff'), ('wand', 'Wand'), ('spear', 'Spear')], max_length=20, null=True),
        ),
    ]
