# Generated by Django 5.2.6 on 2026-06-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_lumentierproperty_heavy_failure_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumenascendrule',
            options={'ordering': ['lumen_tier', 'lumen_level'], 'verbose_name': 'Lumen Ascend Stat Rule', 'verbose_name_plural': 'Lumen Ascend Stat Rules'},
        ),
        migrations.AlterUniqueTogether(
            name='lumenascendrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lumenascendrule',
            name='item_types',
            field=models.JSONField(default=list, help_text='List of item types applicable for this rule'),
        ),
        migrations.RemoveField(
            model_name='lumenascendrule',
            name='item_type',
        ),
    ]
