# Generated by Django 5.2.6 on 2026-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_lumenascendrule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auroralinepool',
            options={'ordering': ['aurora_property', 'aurora_level', 'stat_type', 'line_type', 'value'], 'verbose_name': 'Aurora Line Pool', 'verbose_name_plural': 'Aurora Line Pools'},
        ),
        migrations.RemoveField(
            model_name='auroralinepool',
            name='item_type',
        ),
        migrations.AddField(
            model_name='auroralinepool',
            name='item_types',
            field=models.JSONField(default=list, help_text='List of item types applicable'),
        ),
    ]
