# Generated by Django 5.2.6 on 2026-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_auroralinepool_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auroramodifierrule',
            name='max_aurora_target',
            field=models.IntegerField(default=0, help_text='Max Aurora Level this item can affect (e.g. 0=Rare, 1=Epic, 2=Unique, 3=Legendary)'),
        ),
    ]
