# Generated by Django 5.2.6 on 2026-06-27 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_auroramodifierrule_max_aurora_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auroramodifierrule',
            name='max_aurora_target',
            field=models.IntegerField(default=0, help_text='Max Aurora Level of this item'),
        ),
        migrations.AlterField(
            model_name='auroramodifierrule',
            name='tier_up_chance',
            field=models.FloatField(default=0.0, help_text='Base chance to tier-up (e.g. 0.01 = 1%, 0.1 = 10%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
