# Generated by Django 5.2.6 on 2026-06-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_auroramodifierrule_max_aurora_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtemplate',
            name='max_aurora_lines',
            field=models.IntegerField(default=3, help_text='Maximum number of Aurora lines this item can have'),
        ),
    ]
