# Generated by Django 5.2.6 on 2026-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_itemtemplate_max_aurora_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuroraLineCountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_item_level', models.IntegerField(help_text='Minimum item level to apply this rule', unique=True)),
                ('max_lines', models.IntegerField(default=1, help_text='Max Aurora lines allowed')),
            ],
            options={
                'verbose_name': 'Aurora Line Count Config',
                'verbose_name_plural': 'Aurora Line Count Configs',
                'ordering': ['-min_item_level'],
            },
        ),
        migrations.RemoveField(
            model_name='itemtemplate',
            name='max_aurora_lines',
        ),
    ]
