# Generated by Django 5.2.6 on 2026-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_itemtemplate_asset_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auroramodifierrule',
            name='modifier_type',
            field=models.CharField(choices=[('REROLL_ALL', 'Reroll All Lines (Basic)'), ('REROLL_CHOICE', 'Reroll All Lines & Choose (Before/After)'), ('REROLL_TRIPLE_CHOICE', 'Reroll 3x Lines & Pick N'), ('REROLL_SINGLE', 'Reroll a Single Selected Line'), ('REPLACE_FIXED', 'Replace Single Line with Fixed Stat'), ('FORCE_SET', 'Force Set Aurora Level and Fixed Lines')], max_length=50),
        ),
    ]
