# Generated by Django 5.2.6 on 2026-09-29 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0011_remove_unimplemented_aurora_modifier_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="LumenModifierRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_level",
                    models.PositiveIntegerField(
                        help_text="Lumen Ascend level the gear is set to",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "item_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Gear item types it works on (empty means any)",
                    ),
                ),
                (
                    "item_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lumen_modifier_rule",
                        to="items.itemtemplate",
                    ),
                ),
                (
                    "lumen_tiers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Lumen tiers it works on (empty means any)",
                        to="items.lumentierproperty",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lumen Modifier Rule",
                "verbose_name_plural": "Lumen Modifier Rules",
            },
        ),
    ]
