# Generated by Django 5.2.6 on 2026-09-29 10:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0012_lumenmodifierrule"),
        ("skilles", "0006_effect_damage_power_ratio_per_turn"),
    ]

    operations = [
        migrations.CreateModel(
            name="BattleConsumableRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hp_restore",
                    models.PositiveIntegerField(
                        default=0, help_text="Flat HP restored"
                    ),
                ),
                (
                    "hp_restore_percent",
                    models.FloatField(
                        default=0,
                        help_text="HP restored as a fraction of max HP (0.3 = 30%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "mp_restore",
                    models.PositiveIntegerField(
                        default=0, help_text="Flat MP restored"
                    ),
                ),
                (
                    "mp_restore_percent",
                    models.FloatField(
                        default=0,
                        help_text="MP restored as a fraction of max MP",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("SELF", "Self"), ("ALLY", "Self or a living ally")],
                        default="SELF",
                        max_length=10,
                    ),
                ),
                (
                    "cooldown_turns",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Rounds before this item can be used again (same counting as skill cooldowns)",
                    ),
                ),
                (
                    "applies_effect",
                    models.ForeignKey(
                        blank=True,
                        help_text="Effect applied to the target, e.g. an ATT buff",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="skilles.effecttemplate",
                    ),
                ),
                (
                    "item_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_consumable_rule",
                        to="items.itemtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Battle Consumable Rule",
                "verbose_name_plural": "Battle Consumable Rules",
            },
        ),
    ]
