# Generated by Django 5.2.6 on 2026-09-29 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0013_battleconsumablerule"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimedBuffRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exp_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="EXP gain bonus in % (100 = x2)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "lumis_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="Lumis gain bonus in % (100 = x2)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "drop_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="Common drop rate bonus in % (100 = x2)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "epic_drop_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="Epic drop rate bonus in % (100 = x2). Legendary drops are never boosted",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Buff time added by one use",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Most time the buff may have left after a use; empty means no limit",
                        null=True,
                    ),
                ),
                (
                    "item_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timed_buff_rule",
                        to="items.itemtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timed Buff Rule",
                "verbose_name_plural": "Timed Buff Rules",
            },
        ),
    ]
