# Generated by Django 5.2.6 on 2026-09-29 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_gain_rate_buffs"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuroraLumisCostRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_item_level",
                    models.IntegerField(
                        default=0,
                        help_text="Applies to items whose minimum level is at least this",
                    ),
                ),
                (
                    "aurora_level",
                    models.PositiveIntegerField(
                        help_text="Current Aurora level of the item",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "lumis_cost",
                    models.PositiveBigIntegerField(
                        help_text="Lumis charged per reroll"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aurora Lumis Cost Rule",
                "verbose_name_plural": "Aurora Lumis Cost Rules",
                "ordering": ["aurora_level", "-min_item_level"],
                "unique_together": {("min_item_level", "aurora_level")},
            },
        ),
    ]
