# Generated by Django 5.2.6 on 2026-09-30 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0015_auroralumiscostrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtemplate",
            name="expire_after_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Each copy expires this long after it is received (empty = no relative limit)",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Every copy expires at this moment, e.g. the end of an event (empty = no fixed limit)",
                null=True,
            ),
        ),
    ]
