# Generated by Django 5.2.6 on 2026-09-30 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0016_item_time_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="timedbuffrule",
            name="final_damage_bonus",
            field=models.FloatField(
                default=0,
                help_text="Final damage bonus in % (20 = all damage dealt x1.2); heals are not affected",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
