# Generated by Django 5.2.6 on 2026-09-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0017_final_damage_and_passives"),
    ]

    operations = [
        migrations.CreateModel(
            name="FragmentRestoreRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fragment_restore_rule",
                        to="items.itemtemplate",
                    ),
                ),
                (
                    "restorable_items",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Gear it restores (empty means any)",
                        limit_choices_to=models.Q(
                            ("item_type__in", ("use", "etc")), _negated=True
                        ),
                        related_name="restored_by_rules",
                        to="items.itemtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fragment Restore Rule",
                "verbose_name_plural": "Fragment Restore Rules",
            },
        ),
    ]
