# Generated by Django 5.2.6 on 2026-06-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_turns', models.IntegerField(default=1)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/icons/effects')),
                ('stacking_rule', models.CharField(choices=[('REFRESH', 'Refresh Duration'), ('INDEPENDENT', 'Independent Stacks'), ('UPGRADE', 'Upgrade Effect'), ('NO_STACK', 'No Stacking')], default='REFRESH', max_length=15)),
                ('flat_hp_change', models.IntegerField(default=0)),
                ('percent_hp_change', models.FloatField(default=0)),
                ('flat_mp_change', models.IntegerField(default=0)),
                ('percent_mp_change', models.FloatField(default=0)),
                ('flat_att_change', models.IntegerField(default=0)),
                ('percent_att_change', models.FloatField(default=0)),
                ('flat_str_change', models.IntegerField(default=0)),
                ('percent_str_change', models.FloatField(default=0)),
                ('flat_agi_change', models.IntegerField(default=0)),
                ('percent_agi_change', models.FloatField(default=0)),
                ('flat_int_change', models.IntegerField(default=0)),
                ('percent_int_change', models.FloatField(default=0)),
                ('drop_rate_change', models.FloatField(default=0)),
                ('exp_rate_change', models.FloatField(default=0)),
                ('final_damage_modifier', models.FloatField(default=0, help_text='Final damage percent modifier, positive for buff, negative for debuff')),
                ('shields_points', models.IntegerField(default=0, help_text='Amount of damage the shield can absorb')),
                ('cooldown_reduction', models.IntegerField(default=0, help_text='Reduction in skill cooldown in turns')),
                ('hp_change_per_turn', models.IntegerField(default=0)),
                ('mp_change_per_turn', models.IntegerField(default=0)),
                ('damage_taken_modifier', models.FloatField(default=0, help_text='Modifier to damage taken, positive to increase damage taken, negative to reduce damage taken')),
                ('damage_dealt_modifier', models.FloatField(default=0, help_text='Modifier to damage dealt, positive to increase damage dealt, negative to reduce damage dealt')),
                ('health_received_modifier', models.FloatField(default=0, help_text='Modifier to health received from healing, positive to increase healing received, negative to reduce healing received')),
                ('mana_received_modifier', models.FloatField(default=0, help_text='Modifier to mana received from mana restoration, positive to increase mana received, negative to reduce mana received')),
                ('health_dealt_modifier', models.FloatField(default=0, help_text='Modifier to health dealt by caster, positive to increase health dealt, negative to reduce health dealt')),
                ('mana_dealt_modifier', models.FloatField(default=0, help_text='Modifier to mana dealt by caster, positive to increase mana dealt, negative to reduce mana dealt')),
                ('dispellable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialEffectTag',
            fields=[
                ('id', models.CharField(help_text='Unique identifier for the special effect', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.IntegerField(default=1)),
                ('mp_cost', models.IntegerField(default=0)),
                ('cooldown', models.IntegerField(default=0)),
                ('target_type', models.CharField(choices=[('SELF', 'Self'), ('ALLY', 'Single Ally'), ('ENEMY', 'Single Enemy'), ('E_AREA', 'Enemy Area'), ('A_AREA', 'Ally Area'), ('GLOBAL', 'Global')], default='ENEMY', max_length=10)),
                ('effect_type', models.CharField(choices=[('DAMAGE', 'Deal Damage'), ('HEAL', 'Healing'), ('EFFECT', 'Apply Effect')], default='DAMAGE', max_length=10)),
                ('base_power', models.FloatField(default=0)),
                ('power_ratio', models.FloatField(default=0)),
                ('applies_effect', models.ForeignKey(blank=True, help_text='Effect applied by the skill', null=True, on_delete=django.db.models.deletion.SET_NULL, to='skilles.effecttemplate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='classes.job')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='effecttemplate',
            name='special_effects',
            field=models.ManyToManyField(blank=True, related_name='effects', to='skilles.specialeffecttag'),
        ),
    ]
