# Generated by Django 5.2.6 on 2026-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='effecttemplate',
            name='lumis_rate_change',
            field=models.FloatField(default=0, help_text='Lumis gain rate change, positive for buff, negative for debuff'),
        ),
    ]
