# Generated by Django 5.2.6 on 2026-09-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilles', '0002_add_lumis_rate_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.IntegerField(help_text='Which level of the skill this config applies to. 1 = first unlock.')),
                ('required_char_level', models.IntegerField(help_text='Character must be at or above this level to unlock/upgrade this skill level.')),
                ('damage_multiplier', models.FloatField(default=1.0, help_text='Damage multiplier at this skill level applied to the base skill damage formula. e.g. 1.0 = 100%, 1.5 = 150%, 1.75 = 175%.')),
                ('required_materials', models.JSONField(blank=True, default=list, help_text='List of materials required for manual upgrade. Empty means auto-upgrade on level-up. Format: [{"item_template_id": 1, "quantity": 5}, ...]')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_configs', to='skilles.skilltemplate')),
            ],
            options={
                'verbose_name': 'Skill Level Config',
                'verbose_name_plural': 'Skill Level Configs',
                'ordering': ['skill', 'skill_level'],
                'unique_together': {('skill', 'skill_level')},
            },
        ),
    ]
