# Generated by Django 5.2.6 on 2026-09-17 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilles', '0005_skilltemplate_client_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='effecttemplate',
            name='damage_power_ratio_per_turn',
            field=models.FloatField(default=0, help_text="Damage dealt each turn as a ratio of the caster's current damage. For example, 0.25 deals 25% damage per turn.", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
