# Generated by Django 5.2.6 on 2026-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skilles", "0006_effect_damage_power_ratio_per_turn"),
    ]

    operations = [
        migrations.AddField(
            model_name="effecttemplate",
            name="dispel_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="When applied, removes up to this many dispellable effects: debuffs from an ally, buffs from an enemy",
            ),
        ),
        migrations.AddField(
            model_name="effecttemplate",
            name="effect_kind",
            field=models.CharField(
                choices=[("BUFF", "Buff"), ("DEBUFF", "Debuff")],
                default="BUFF",
                help_text="Dispels remove debuffs from allies and buffs from enemies",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="cooldown_reduction",
            field=models.IntegerField(
                default=0,
                help_text="While active, skills the target uses go on cooldown this many turns shorter",
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="dispellable",
            field=models.BooleanField(
                default=True, help_text="Whether a dispel can remove this effect"
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="duration_turns",
            field=models.IntegerField(
                default=1,
                help_text="Turns of the target it lasts: it ticks at the end of each of the target side's phases, skipping the phase it was applied in. 0 = instant (e.g. a pure dispel).",
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="flat_hp_change",
            field=models.IntegerField(
                default=0,
                help_text="Max HP change while active, positive for buff, negative for debuff",
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="flat_mp_change",
            field=models.IntegerField(
                default=0,
                help_text="Max MP change while active, positive for buff, negative for debuff",
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="percent_hp_change",
            field=models.FloatField(
                default=0,
                help_text="Max HP change as a fraction (0.2 = +20%) while active",
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="percent_mp_change",
            field=models.FloatField(
                default=0,
                help_text="Max MP change as a fraction (0.2 = +20%) while active",
            ),
        ),
    ]
