# Generated by Django 5.2.6 on 2026-09-29 18:10

from django.db import migrations


# Combat looks these tags up by id (SpecialEffectTag.STUN / SILENCE).
TAGS = {
    'stun': ('Stun', 'The target loses its turns while stunned.'),
    'silence': ('Silence', 'The target can only use basic attacks and items.'),
}


def seed_tags(apps, schema_editor):
    SpecialEffectTag = apps.get_model('skilles', 'SpecialEffectTag')
    for tag_id, (name, description) in TAGS.items():
        SpecialEffectTag.objects.get_or_create(
            id=tag_id, defaults={'name': name, 'description': description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("skilles", "0007_effect_kind_and_dispel"),
    ]

    operations = [
        migrations.RunPython(seed_tags, migrations.RunPython.noop),
    ]
