# Generated by Django 5.2.6 on 2026-09-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skilles", "0008_seed_stun_silence_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="effecttemplate",
            name="drop_rate_change",
            field=models.FloatField(
                default=0,
                help_text="Common drop rate change in % (100 = x2); negative for a debuff",
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="exp_rate_change",
            field=models.FloatField(
                default=0,
                help_text="EXP gain change in % (100 = x2); negative for a debuff",
            ),
        ),
        migrations.AlterField(
            model_name="effecttemplate",
            name="lumis_rate_change",
            field=models.FloatField(
                default=0,
                help_text="Lumis gain change in % (100 = x2); negative for a debuff",
            ),
        ),
    ]
