# Generated by Django 5.2.6 on 2026-09-30 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skilles", "0009_rate_change_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilllevelconfig",
            name="final_damage_bonus",
            field=models.FloatField(
                default=0.0,
                help_text="Passive skills only: final damage added to the boosted skills at this level (0.2 = +20%).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="skilltemplate",
            name="boosted_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Passive only: skills whose final damage it raises. Empty = every damage skill.",
                related_name="boosted_by",
                to="skilles.skilltemplate",
            ),
        ),
        migrations.AlterField(
            model_name="skilltemplate",
            name="effect_type",
            field=models.CharField(
                choices=[
                    ("DAMAGE", "Deal Damage"),
                    ("HEAL", "Healing"),
                    ("EFFECT", "Apply Effect"),
                    ("PASSIVE", "Passive (always on)"),
                ],
                default="DAMAGE",
                max_length=10,
            ),
        ),
    ]
