# Generated by Django 5.2.6 on 2026-10-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skilles", "0010_final_damage_and_passives"),
    ]

    operations = [
        migrations.AddField(
            model_name="effecttemplate",
            name="icon_key",
            field=models.CharField(
                blank=True,
                help_text="Stable frontend key for the effect icon.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
