# Generated by Django 5.2.6 on 2026-06-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('main_stat', models.CharField(choices=[('str', 'Strength'), ('agi', 'Agility'), ('int', 'Intelligence'), ('all', 'All Stats')], help_text='Main stat for the class', max_length=3)),
                ('hp_growth', models.FloatField(default=0)),
                ('mp_growth', models.FloatField(default=0)),
                ('str_growth', models.FloatField(default=0)),
                ('agi_growth', models.FloatField(default=0)),
                ('int_growth', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('att_weight', models.FloatField(default=1.0, help_text='Damage gain each att point')),
                ('main_stat_weight', models.FloatField(default=1.0, help_text='Damage gain each main stat point')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.characterclass')),
            ],
        ),
    ]
