# Generated by Django 5.2.6 on 2026-06-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='att_weight',
        ),
        migrations.RemoveField(
            model_name='job',
            name='main_stat_weight',
        ),
    ]
