# Generated by Django 5.2.6 on 2026-06-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_remove_job_att_weight_remove_job_main_stat_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='main_stat_weight',
            field=models.FloatField(default=1.0, help_text='Weight for main stat in damage calculation'),
        ),
    ]
