# Generated by Django 5.2.6 on 2026-09-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_job_main_stat_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="weapon_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1hs", "One Handed Sword"),
                    ("2hs", "Two Handed Sword"),
                    ("1ha", "One Handed Axe"),
                    ("blunt", "Blunt Weapon"),
                    ("bow", "Bow"),
                    ("staff", "Staff"),
                    ("wand", "Wand"),
                    ("spear", "Spear"),
                ],
                help_text="The one weapon type this job can equip. Empty = any weapon (not configured yet).",
                max_length=20,
                null=True,
            ),
        ),
    ]
