# Generated by Django 5.2.6 on 2026-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='receiver_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='receiver_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='sender_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='sender_ready',
            field=models.BooleanField(default=False),
        ),
    ]
