# Generated by Django 5.2.6 on 2026-09-30 03:01

import django.db.models.deletion
from django.db import migrations, models


def backfill_from_listings(apps, schema_editor):
    """Earlier sales had no fee: the seller got the whole listing price."""
    Transaction = apps.get_model('market', 'Transaction')
    for sale in Transaction.objects.select_related('listing__item'):
        listing = sale.listing
        sale.item_template_id = listing.item.template_id if listing.item_id else None
        sale.quantity = listing.quantity
        sale.price = listing.price
        sale.fee = 0
        sale.seller_received = listing.price
        sale.save(update_fields=['item_template', 'quantity', 'price', 'fee', 'seller_received'])


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0015_auroralumiscostrule"),
        ("market", "0002_trade_receiver_accepted_trade_receiver_ready_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="fee",
            field=models.PositiveIntegerField(
                default=0, help_text="Market fee taken from the seller's proceeds"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="item_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="items.itemtemplate",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="price",
            field=models.PositiveIntegerField(
                default=0, help_text="Lumis the buyer paid for the whole listing"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="transaction",
            name="seller_received",
            field=models.PositiveIntegerField(default=0, help_text="price - fee"),
        ),
        migrations.RunPython(backfill_from_listings, migrations.RunPython.noop),
    ]
