# Generated by Django 5.2.6 on 2026-06-27 11:01

import apps.characters.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.CharField(default=apps.characters.models.generate_hex_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('max_size', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_parties', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='PartyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='party.party')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='characters.character')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='PendingPartyLoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dropped_at', models.DateTimeField(auto_now_add=True)),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_loots', to='party.party')),
            ],
            options={
                'verbose_name': 'Pending Party Loot',
                'verbose_name_plural': 'Pending Party Loots',
                'ordering': ['-dropped_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to='characters.character')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_members', to='party.party')),
            ],
            options={
                'ordering': ['party', 'position'],
                'unique_together': {('party', 'character'), ('party', 'position')},
            },
        ),
    ]
