# Generated by Django 5.2.6 on 2026-09-29 08:06

from django.db import migrations, models


def mark_existing_solo_parties(apps, schema_editor):
    # Normal-dungeon entry was the only code creating parties with max_size=1;
    # create_party always used 4.
    Party = apps.get_model("party", "Party")
    Party.objects.filter(max_size=1).update(is_solo=True)


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="is_solo",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_solo_parties, migrations.RunPython.noop),
    ]
