# Generated by Django 5.2.6 on 2026-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_unique_character_name"),
        ("party", "0002_party_is_solo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="partymember",
            constraint=models.UniqueConstraint(
                fields=("character",), name="one_party_per_character"
            ),
        ),
    ]
