# Generated by Django 5.2.6 on 2026-06-27 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('items', '0001_initial'),
        ('skilles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossDungeonTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.IntegerField(default=1)),
                ('exp_reward', models.IntegerField(default=0)),
                ('lumis_reward', models.IntegerField(default=0)),
                ('max_party_size', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('time_type', models.CharField(choices=[('daily', 'Can be done once per day'), ('weekly', 'Can be done once per week'), ('monthly', 'Can be done once per month')], default='daily', max_length=10)),
            ],
            options={
                'verbose_name': 'Boss Dungeon Template',
                'verbose_name_plural': 'Boss Dungeon Templates',
                'ordering': ['required_level', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('required_exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.IntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DungeonClearLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_clears', to='characters.character')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clear_logs', to='world.bossdungeontemplate')),
            ],
            options={
                'verbose_name': 'Dungeon Clear Log',
                'verbose_name_plural': 'Dungeon Clear Logs',
                'ordering': ['-cleared_at'],
            },
        ),
        migrations.CreateModel(
            name='EnemyTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('is_boss', models.BooleanField(default=False)),
                ('base_hp', models.IntegerField()),
                ('base_mp', models.IntegerField()),
                ('base_att', models.IntegerField()),
                ('exp_reward', models.IntegerField()),
                ('lumis_reward_min', models.IntegerField()),
                ('lumis_reward_max', models.IntegerField()),
                ('skills', models.ManyToManyField(blank=True, related_name='enemies', to='skilles.skilltemplate')),
            ],
        ),
        migrations.AddField(
            model_name='bossdungeontemplate',
            name='enemies',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_stages', to='world.enemytemplate'),
        ),
        migrations.CreateModel(
            name='NormalDungeonTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.IntegerField(default=1)),
                ('exp_reward', models.IntegerField(default=0)),
                ('lumis_reward', models.IntegerField(default=0)),
                ('stamina_cost', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('enemies', models.ManyToManyField(blank=True, related_name='%(class)s_stages', to='world.enemytemplate')),
            ],
            options={
                'verbose_name': 'Normal Dungeon Template',
                'verbose_name_plural': 'Normal Dungeon Templates',
                'ordering': ['required_level', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('required_level', models.IntegerField(default=1)),
                ('has_shop', models.BooleanField(default=False, help_text='Whether this location has an NPC shop')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within region')),
                ('boss_dungeon', models.ForeignKey(blank=True, help_text='Linked boss dungeon, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='world.bossdungeontemplate')),
                ('field_enemies', models.ManyToManyField(blank=True, help_text='Enemies that can be encountered in the field', related_name='field_locations', to='world.enemytemplate')),
                ('normal_dungeon', models.ForeignKey(blank=True, help_text='Linked normal dungeon, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='world.normaldungeontemplate')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='world.region')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['region', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LootTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_drop_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(default=1)),
                ('drop_type', models.CharField(choices=[('common', 'Easily dropped, gain a lot of drop increase'), ('epic', 'Hard to drop, can only boosted by specific consumable item and limited events'), ('legendary', 'Very rare, cannot increase drop rate')], default='common', max_length=10)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_tables', to='world.enemytemplate')),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate')),
            ],
            options={
                'verbose_name': 'Loot Table',
                'verbose_name_plural': 'Loot Tables',
                'ordering': ['enemy', 'item_template'],
                'unique_together': {('enemy', 'item_template')},
            },
        ),
    ]
