# Generated by Django 5.2.6 on 2026-06-27 15:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bossdungeontemplate',
            name='enemies',
        ),
        migrations.RemoveField(
            model_name='normaldungeontemplate',
            name='enemies',
        ),
        migrations.AlterField(
            model_name='bossdungeontemplate',
            name='max_party_size',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='bossdungeontemplate',
            name='time_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
        migrations.CreateModel(
            name='BossStageEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, help_text='Number of enemies of this type. Max 6.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_stage_appearances', to='world.enemytemplate')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_enemies', to='world.bossdungeontemplate')),
            ],
            options={
                'verbose_name': 'Boss Stage Enemy',
                'verbose_name_plural': 'Boss Stage Enemies',
                'unique_together': {('stage', 'enemy')},
            },
        ),
        migrations.CreateModel(
            name='NormalStageEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, help_text='Number of enemies of this type. Max 6.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_stage_appearances', to='world.enemytemplate')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_enemies', to='world.normaldungeontemplate')),
            ],
            options={
                'verbose_name': 'Normal Stage Enemy',
                'verbose_name_plural': 'Normal Stage Enemies',
                'unique_together': {('stage', 'enemy')},
            },
        ),
    ]
