# Generated by Django 5.2.6 on 2026-06-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_remove_bossdungeontemplate_enemies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossdungeontemplate',
            name='enemies',
            field=models.ManyToManyField(blank=True, related_name='boss_stages', through='world.BossStageEnemy', to='world.enemytemplate'),
        ),
        migrations.AddField(
            model_name='normaldungeontemplate',
            name='enemies',
            field=models.ManyToManyField(blank=True, related_name='normal_stages', through='world.NormalStageEnemy', to='world.enemytemplate'),
        ),
    ]
