# Generated by Django 5.2.6 on 2026-09-30 04:40

import django.db.models.deletion
from django.db import migrations, models


def copy_location_links_to_dungeons(apps, schema_editor):
    """Locations used to point at a dungeon; now each dungeon names its location."""
    Location = apps.get_model('world', 'Location')
    for location in Location.objects.order_by('region__order', 'order', 'id'):
        for field in ('normal_dungeon', 'boss_dungeon'):
            dungeon = getattr(location, field)
            # A dungeon linked from several locations keeps the first one.
            if dungeon is not None and dungeon.location_id is None:
                dungeon.location = location
                dungeon.save(update_fields=['location'])


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0003_bossdungeontemplate_enemies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bossdungeontemplate",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="boss_dungeons",
                to="world.location",
            ),
        ),
        migrations.AddField(
            model_name="normaldungeontemplate",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="normal_dungeons",
                to="world.location",
            ),
        ),
        migrations.RunPython(copy_location_links_to_dungeons, migrations.RunPython.noop),
    ]
