# Generated by Django 5.2.6 on 2026-09-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0004_dungeon_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="boss_dungeon",
        ),
        migrations.RemoveField(
            model_name="location",
            name="field_enemies",
        ),
        migrations.RemoveField(
            model_name="location",
            name="has_shop",
        ),
        migrations.RemoveField(
            model_name="location",
            name="normal_dungeon",
        ),
        migrations.RemoveField(
            model_name="location",
            name="required_level",
        ),
        migrations.RemoveField(
            model_name="region",
            name="required_level",
        ),
    ]
