# Generated by Django 5.2.6 on 2026-10-04 07:03

from django.db import migrations, models


def number_existing(apps, schema_editor):
    # Keep the order players saw before: by required level, then creation.
    for name in ('NormalDungeonTemplate', 'BossDungeonTemplate'):
        model = apps.get_model('world', name)
        for position, dungeon in enumerate(model.objects.order_by('required_level', 'id'), start=1):
            model.objects.filter(pk=dungeon.pk).update(order=position)


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0005_world_locations_are_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bossdungeontemplate",
            options={
                "ordering": ["order", "required_level", "id"],
                "verbose_name": "Boss Dungeon Template",
                "verbose_name_plural": "Boss Dungeon Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="normaldungeontemplate",
            options={
                "ordering": ["order", "required_level", "id"],
                "verbose_name": "Normal Dungeon Template",
                "verbose_name_plural": "Normal Dungeon Templates",
            },
        ),
        migrations.AddField(
            model_name="bossdungeontemplate",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Display order"),
        ),
        migrations.AddField(
            model_name="normaldungeontemplate",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Display order"),
        ),
        migrations.RunPython(number_existing, migrations.RunPython.noop),
    ]
