# Generated by Django 5.2.6 on 2026-06-27 11:01

import apps.characters.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bonus_final_damage', models.FloatField(default=0.0, help_text='Bonus final damage multiplier for this specific skill (e.g. 0.2 for +20% dmg)')),
            ],
            options={
                'verbose_name': 'Character Skill',
                'verbose_name_plural': 'Character Skills',
                'ordering': ['character', 'skill_template'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(help_text="Internal identifier, e.g. 'hat', 'ring', 'weapon'", max_length=30, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable name, e.g. 'Hat', 'Ring', 'Weapon'", max_length=50)),
                ('max_count', models.PositiveIntegerField(default=1, help_text='How many items can be equipped in this slot type (e.g. 4 for rings)')),
                ('allowed_item_types', models.JSONField(default=list, help_text="List of item_type values allowed in this slot, e.g. ['hat'] or ['ring']")),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in equipment UI')),
            ],
            options={
                'verbose_name': 'Equipment Slot Config',
                'verbose_name_plural': 'Equipment Slot Configs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EquippedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_index', models.PositiveIntegerField(default=0, help_text='Index within the slot (0 for single slots, 0-3 for 4-slot rings)')),
            ],
            options={
                'verbose_name': 'Equipped Item',
                'verbose_name_plural': 'Equipped Items',
                'ordering': ['slot__order', 'slot_index'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.CharField(default=apps.characters.models.generate_hex_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('base_hp', models.IntegerField(default=50)),
                ('base_mp', models.IntegerField(default=5)),
                ('base_att', models.IntegerField(default=5)),
                ('base_str', models.IntegerField(default=10)),
                ('base_agi', models.IntegerField(default=10)),
                ('base_int', models.IntegerField(default=10)),
                ('drop_rate', models.FloatField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('current_exp', models.IntegerField(default=0)),
                ('max_stamina', models.IntegerField(default=120)),
                ('current_stamina', models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('last_stamina_update', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time stamina was updated')),
                ('character_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.characterclass')),
            ],
        ),
    ]
