# Generated by Django 5.2.6 on 2026-06-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('classes', '0001_initial'),
        ('inventory', '0001_initial'),
        ('skilles', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='current_location',
            field=models.ForeignKey(blank=True, help_text="Character's current location in the world", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_here', to='world.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.job'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='characters.character'),
        ),
        migrations.AddField(
            model_name='characterskill',
            name='skill_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilles.skilltemplate'),
        ),
        migrations.AddField(
            model_name='equippeditem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to='characters.character'),
        ),
        migrations.AddField(
            model_name='equippeditem',
            name='item',
            field=models.OneToOneField(help_text='The inventory item that is equipped', on_delete=django.db.models.deletion.CASCADE, related_name='equipped_in', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='equippeditem',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipped_items', to='characters.equipmentslotconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='characterskill',
            unique_together={('character', 'skill_template')},
        ),
        migrations.AlterUniqueTogether(
            name='equippeditem',
            unique_together={('character', 'slot', 'slot_index')},
        ),
    ]
