# Generated by Django 5.2.6 on 2026-09-29 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_initial"),
        ("items", "0014_gain_rate_buffs"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "exp_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="EXP gain bonus in % (100 = x2)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "lumis_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="Lumis gain bonus in % (100 = x2)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "drop_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="Common drop rate bonus in % (100 = x2)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "epic_drop_rate_bonus",
                    models.FloatField(
                        default=0,
                        help_text="Epic drop rate bonus in % (100 = x2)",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Event",
                "verbose_name_plural": "Rate Events",
            },
        ),
        migrations.CreateModel(
            name="CharacterBuff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exp_rate_bonus", models.FloatField(default=0)),
                ("lumis_rate_bonus", models.FloatField(default=0)),
                ("drop_rate_bonus", models.FloatField(default=0)),
                ("epic_drop_rate_bonus", models.FloatField(default=0)),
                ("started_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buffs",
                        to="characters.character",
                    ),
                ),
                (
                    "source_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="items.itemtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Character Buff",
                "verbose_name_plural": "Character Buffs",
                "ordering": ["expires_at"],
                "unique_together": {("character", "source_template")},
            },
        ),
    ]
