# Generated by Django 5.2.6 on 2026-09-29 18:15

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_gain_rate_buffs"),
        ("classes", "0003_job_main_stat_weight"),
        ("world", "0003_bossdungeontemplate_enemies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(help_text="Unique, ignoring case", max_length=20),
        ),
        migrations.AddConstraint(
            model_name="character",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_character_name_ci",
                violation_error_message="This character name is already taken.",
            ),
        ),
    ]
