# Generated by Django 5.2.6 on 2026-09-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_unique_character_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="current_location",
        ),
    ]
