# Generated by Django 5.2.6 on 2026-09-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_world_locations_are_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="characterskill",
            name="bonus_final_damage",
        ),
        migrations.AddField(
            model_name="characterbuff",
            name="final_damage_bonus",
            field=models.FloatField(default=0),
        ),
    ]
