# Generated by Django 5.2.6 on 2026-09-30 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def record_opening_balances(apps, schema_editor):
    """Nova held before the ledger existed gets one opening entry, so ledger and balance agree."""
    GameUser = apps.get_model('users', 'GameUser')
    NovaTransaction = apps.get_model('users', 'NovaTransaction')
    NovaTransaction.objects.bulk_create([
        NovaTransaction(
            user=user, kind='adjustment', amount=user.nova, balance_after=user.nova,
            note='Opening balance, recorded when the Nova ledger was introduced.',
        )
        for user in GameUser.objects.filter(nova__gt=0)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_character_set_null_on_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="NovaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("donation", "Donation"),
                            ("purchase", "Shop purchase"),
                            ("adjustment", "Admin adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Positive adds Nova, negative takes it away"
                    ),
                ),
                ("balance_after", models.PositiveIntegerField(editable=False)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Donation/payment reference (e.g. the Ko-fi ID). Each can be credited only once.",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Shown to the player, e.g. '2x Potion'",
                        max_length=200,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Internal note, not shown to the player"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nova_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nova Transaction",
                "verbose_name_plural": "Nova Transactions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.RunPython(record_opening_balances, migrations.RunPython.noop),
    ]
