# Generated by Django 5.2.6 on 2026-10-01 03:20

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0006_final_damage_and_passives"),
        ("users", "0003_novatransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameuser",
            name="email",
            field=models.EmailField(
                help_text="Unique regardless of case.", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="gameuser",
            name="username",
            field=models.CharField(
                help_text="3-20 characters: letters, digits, _ and -. Unique regardless of case.",
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\A[A-Za-z0-9_-]{3,20}\\Z",
                        "Username must be 3-20 characters: letters, digits, _ and -.",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="gameuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("username"),
                name="unique_username_ci",
                violation_error_message="This username is already taken.",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_email_ci",
                violation_error_message="This email is already registered.",
            ),
        ),
    ]
