# Generated by Django 5.2.6 on 2026-10-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_case_insensitive_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameuser",
            name="session_version",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
