# Generated by Django 5.2.6 on 2026-10-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Kept when the account is deleted", max_length=255
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Tạo mới"),
                            ("update", "Sửa"),
                            ("delete", "Xóa"),
                            ("action", "Thao tác"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        db_index=True,
                        help_text="Model label, e.g. items.ItemTemplate",
                        max_length=100,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("target_repr", models.CharField(max_length=255)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Studio change",
                "verbose_name_plural": "Studio changes",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
