# Generated by Django 5.2.6 on 2026-06-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lumen_ascend_level', models.IntegerField(default=0)),
                ('aurora_level', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('is_untrade', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='characters.character', verbose_name='Owner')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate', verbose_name='Item Template')),
            ],
        ),
        migrations.CreateModel(
            name='AuroraLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('hp', 'HP'), ('mp', 'MP'), ('att', 'Attack'), ('str', 'Strength'), ('agi', 'Agility'), ('int', 'Intelligence'), ('all', 'All Stats'), ('drop', 'Drop Rate')], max_length=20)),
                ('line_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], max_length=20)),
                ('value', models.FloatField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aurora_lines', to='inventory.inventoryitem')),
            ],
        ),
    ]
