# Generated by Django 5.2.6 on 2026-06-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lumen_ascend_level', models.IntegerField(default=0)),
                ('aurora_level', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('is_untrade', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('is_destroyed', models.BooleanField(default=False, help_text='Item is destroyed (fragment) and cannot be equipped until restored')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='characters.character', verbose_name='Owner')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate', verbose_name='Item Template')),
            ],
        ),
        migrations.CreateModel(
            name='AuroraLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_index', models.IntegerField(default=0, help_text='Index of the line (0, 1, 2) to distinguish lines')),
                ('stat_type', models.CharField(choices=[('hp', 'HP'), ('mp', 'MP'), ('att', 'Attack'), ('str', 'Strength'), ('agi', 'Agility'), ('int', 'Intelligence'), ('all', 'All Stats'), ('drop', 'Drop Rate')], max_length=20)),
                ('line_type', models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent')], max_length=20)),
                ('value', models.FloatField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aurora_lines', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='PendingAuroraRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_type', models.CharField(help_text='The type of modifier used (e.g. REROLL_CHOICE, REROLL_TRIPLE_CHOICE)', max_length=50)),
                ('generated_lines_data', models.JSONField(default=list, help_text='JSON storing the newly rolled lines data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_aurora_roll', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Pending Aurora Roll',
                'verbose_name_plural': 'Pending Aurora Rolls',
            },
        ),
    ]
