# Generated by Django 5.2.6 on 2026-06-27 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auroraline',
            name='line_index',
            field=models.IntegerField(default=0, help_text='Index of the line (0, 1, 2) to distinguish lines'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_destroyed',
            field=models.BooleanField(default=False, help_text='Item is destroyed (fragment) and cannot be equipped until restored'),
        ),
        migrations.CreateModel(
            name='PendingAuroraRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_type', models.CharField(help_text='The type of modifier used (e.g. REROLL_CHOICE, REROLL_TRIPLE_CHOICE)', max_length=50)),
                ('generated_lines_data', models.JSONField(default=list, help_text='JSON storing the newly rolled lines data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_aurora_roll', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Pending Aurora Roll',
                'verbose_name_plural': 'Pending Aurora Rolls',
            },
        ),
    ]
