# Generated by Django 5.2.6 on 2026-09-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingauroraroll",
            name="new_aurora_level",
            field=models.IntegerField(
                blank=True,
                help_text="Aurora level of the rolled lines (a tier-up). Applied only if the new lines are taken.",
                null=True,
            ),
        ),
    ]
