# Generated by Django 5.2.6 on 2026-10-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0007_character_name_rules"),
        ("inventory", "0002_pendingauroraroll_new_aurora_level"),
        ("items", "0018_fragment_restore_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoldItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price",
                    models.PositiveIntegerField(
                        help_text="Lumis paid for the sale, and charged to buy it back"
                    ),
                ),
                ("lumen_ascend_level", models.IntegerField(default=0)),
                ("aurora_level", models.IntegerField(default=0)),
                (
                    "aurora_lines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{line_index, stat_type, line_type, value}]",
                    ),
                ),
                ("is_untrade", models.BooleanField(default=False)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("sold_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_items",
                        to="characters.character",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="items.itemtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_at", "-id"],
            },
        ),
    ]
