# Generated by Django 5.2.6 on 2026-06-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0002_initial'),
        ('items', '0001_initial'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(choices=[('main', 'Main Quest'), ('side', 'Side Quest'), ('daily', 'Daily Quest'), ('weekly', 'Weekly Quest'), ('event', 'Event Quest')], default='side', max_length=10)),
                ('required_level', models.IntegerField(default=1)),
                ('exp_reward', models.IntegerField(default=0)),
                ('lumis_reward', models.IntegerField(default=0)),
                ('prerequisite_quests', models.ManyToManyField(blank=True, related_name='unlocks_quests', to='quests.questtemplate')),
            ],
            options={
                'verbose_name': 'Quest Template',
                'verbose_name_plural': 'Quest Templates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuestReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='quests.questtemplate')),
            ],
            options={
                'verbose_name': 'Quest Reward',
                'verbose_name_plural': 'Quest Rewards',
                'ordering': ['quest', 'item_template'],
            },
        ),
        migrations.CreateModel(
            name='QuestObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defeat_count', models.IntegerField(default=0)),
                ('collect_count', models.IntegerField(default=0)),
                ('clear_count', models.IntegerField(default=0)),
                ('dungeon_to_clear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.normaldungeontemplate')),
                ('enemy_to_defeat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.enemytemplate')),
                ('item_to_collect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='quests.questtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('claimed', 'Reward Claimed')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='characters.character')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_quests', to='quests.questtemplate')),
            ],
            options={
                'verbose_name': 'Character Quest',
                'verbose_name_plural': 'Character Quests',
                'ordering': ['-started_at'],
                'unique_together': {('character', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='CharacterQuestObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('character_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_progress', to='quests.characterquest')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.questobjective')),
            ],
            options={
                'verbose_name': 'Quest Objective Progress',
                'verbose_name_plural': 'Quest Objective Progress',
                'ordering': ['character_quest', 'objective'],
                'unique_together': {('character_quest', 'objective')},
            },
        ),
    ]
