# Generated by Django 5.2.6 on 2026-06-28 10:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
        ('world', '0003_bossdungeontemplate_enemies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterquest',
            name='last_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Used to track daily/weekly resets'),
        ),
        migrations.AddField(
            model_name='questobjective',
            name='boss_clear_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questobjective',
            name='boss_dungeon_to_clear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='world.bossdungeontemplate'),
        ),
        migrations.AlterField(
            model_name='questtemplate',
            name='quest_type',
            field=models.CharField(choices=[('daily', 'Daily Quest'), ('weekly', 'Weekly Quest'), ('once', 'One-time Quest')], default='once', max_length=10),
        ),
    ]
