# Generated by Django 5.2.6 on 2026-06-27 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('currency_type', models.CharField(choices=[('lumis', 'Lumis'), ('nova', 'Nova')], default='lumis', max_length=10)),
                ('required_level', models.PositiveIntegerField(default=1, help_text='Minimum level required to access this category')),
                ('start_date', models.DateTimeField(blank=True, help_text='Null means always available', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Null means always available', null=True)),
            ],
            options={
                'verbose_name': 'Shop Category',
                'verbose_name_plural': 'Shop Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveBigIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0, help_text='0 means unlimited stock')),
                ('order', models.PositiveIntegerField(default=0)),
                ('required_level', models.PositiveIntegerField(default=1, help_text='Minimum level required to purchase this item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='shops.shopcategory')),
                ('item_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate')),
            ],
            options={
                'verbose_name': 'Shop Item',
                'verbose_name_plural': 'Shop Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialShopItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(help_text='Item endgame', on_delete=django.db.models.deletion.CASCADE, related_name='special_shop_items', to='items.itemtemplate')),
            ],
            options={
                'verbose_name': 'Special Shop Item',
                'verbose_name_plural': 'Special Shop Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialShopItemRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(help_text='Item required for exchange', on_delete=django.db.models.deletion.CASCADE, to='items.itemtemplate')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.specialshopitem')),
            ],
            options={
                'verbose_name': 'Special Shop Item Recipe',
                'verbose_name_plural': 'Special Shop Item Recipes',
                'ordering': ['recipe', 'item'],
                'unique_together': {('recipe', 'item')},
            },
        ),
        migrations.AddField(
            model_name='specialshopitem',
            name='exchange',
            field=models.ManyToManyField(related_name='+', through='shops.SpecialShopItemRecipe', to='items.itemtemplate'),
        ),
    ]
