# Generated by Django 5.2.6 on 2026-06-27 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='reset_cycle',
            field=models.CharField(choices=[('none', 'None (Lifetime)'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited stock per user per cycle'),
        ),
        migrations.CreateModel(
            name='UserShopPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_bought', models.PositiveIntegerField(default=0)),
                ('last_purchased_at', models.DateTimeField(auto_now=True)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Shop Purchase',
                'verbose_name_plural': 'User Shop Purchases',
                'unique_together': {('user', 'shop_item')},
            },
        ),
    ]
