# Generated by Django 5.2.6 on 2026-09-30 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_specialshop"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="specialshopitem",
            name="exchange_limit",
            field=models.PositiveIntegerField(
                default=0, help_text="Exchanges per account per period; 0 = unlimited"
            ),
        ),
        migrations.AddField(
            model_name="specialshopitem",
            name="reset_cycle",
            field=models.CharField(
                choices=[
                    ("none", "None (Lifetime)"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                help_text="When the count resets. For an event shop it also resets when a new run starts.",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="UserSpecialShopExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_exchanged", models.PositiveIntegerField(default=0)),
                ("last_exchanged_at", models.DateTimeField(auto_now=True)),
                (
                    "special_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="shops.specialshopitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_shop_exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Special Shop Exchange",
                "verbose_name_plural": "User Special Shop Exchanges",
                "unique_together": {("user", "special_item")},
            },
        ),
    ]
