# Generated by Django 5.2.6 on 2026-06-27 11:01

import apps.battles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('skilles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatInstance',
            fields=[
                ('id', models.CharField(default=apps.battles.models.generate_hex_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('current_player_position', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('victory', 'Victory'), ('defeat', 'Defeat')], default='in_progress', max_length=20)),
                ('turn_phase', models.CharField(choices=[('player_phase', 'Player Phase'), ('monster_phase', 'Monster Phase')], default='player_phase', help_text='Current phase of the turn', max_length=20)),
                ('turn_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Combatant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objects_id', models.CharField(max_length=100)),
                ('is_player', models.BooleanField(default=True)),
                ('current_hp', models.IntegerField()),
                ('current_mp', models.IntegerField()),
                ('position', models.PositiveIntegerField()),
                ('skill_cooldowns', models.JSONField(blank=True, default=dict, help_text='Stores current cooldowns: {skill_id: turns_left}')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ActiveEffect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remaining_turns', models.IntegerField()),
                ('current_stacks', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effect_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skilles.effecttemplate')),
                ('caster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casted_effects', to='battles.combatant')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effects', to='battles.combatant')),
            ],
            options={
                'verbose_name': 'Active Effect',
                'verbose_name_plural': 'Active Effects',
                'ordering': ['-created_at'],
            },
        ),
    ]
