# Generated by Django 5.2.6 on 2026-06-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('battles', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatinstance',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_instances', to='party.party'),
        ),
        migrations.AddField(
            model_name='combatant',
            name='combat_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combatants', to='battles.combatinstance'),
        ),
        migrations.AddField(
            model_name='activeeffect',
            name='combat_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_effects', to='battles.combatinstance'),
        ),
        migrations.AlterUniqueTogether(
            name='combatant',
            unique_together={('combat_instance', 'position')},
        ),
    ]
