# Generated by Django 5.2.6 on 2026-06-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeeffect',
            name='remaining_shield_points',
            field=models.IntegerField(default=0),
        ),
    ]
