# Generated by Django 5.2.6 on 2026-09-29 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0004_combatinstance_deferred_stamina"),
        ("characters", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatinstance",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BattleActionReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_action_id", models.UUIDField()),
                ("response_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="battle_action_receipts",
                        to="characters.character",
                    ),
                ),
                (
                    "combat_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_receipts",
                        to="battles.combatinstance",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("combat_instance", "client_action_id"),
                        name="unique_battle_action_receipt",
                    )
                ],
            },
        ),
    ]
