# Generated by Django 5.2.6 on 2026-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0005_combat_version_and_action_receipts"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatinstance",
            name="turn_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
