# Generated by Django 5.2.6 on 2026-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0006_combat_turn_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="activeeffect",
            name="skip_next_tick",
            field=models.BooleanField(default=False),
        ),
    ]
