# Generated by Django 5.2.6 on 2026-09-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("battles", "0007_activeeffect_skip_next_tick"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatant",
            name="has_left",
            field=models.BooleanField(default=False),
        ),
    ]
